slogan: What will you make?

theme: bootstrap
inverse: true

menu:
  - title: 归档
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: 分类
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: 标签
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: 关于
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: maker.iee.io
    url: http://maker.iee.io/
    intro: "本站地址"
    icon: "fa fa-user"
  - title: imaker.iee.io (校园网内)
    url: http://imaker.iee.io/
    intro: "本站地址"
    icon: "fa fa-user"
  - title: "编辑本网站"
    url: http://github.com/omaker/makersite
    intro: "On Github."
    icon: "fa fa-github"

widgets:
- category
- tagcloud
- recent_posts  
- links
  # - search

rss: 
fancybox: true
favicon: favicon.png
duoshuo_shortname: imaker

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: true
jiathis: false

